"""empty message

Revision ID: 3e908863b911
Revises: 282e06799d08
Create Date: 2015-10-07 15:38:43.869530

"""

# revision identifiers, used by Alembic.
revision = '3e908863b911'
down_revision = '282e06799d08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_name', sa.String(length=20), nullable=False),
                    sa.Column('description', sa.String(length=200), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tracking_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('pn', sa.String(length=20)),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
                    # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # op.alter_column(u'users', 'email',
    #            existing_type=sa.VARCHAR(length=64),
    #            nullable=True)
    # op.alter_column(u'users', 'password_hash',
    #            existing_type=sa.VARCHAR(length=128),
    #            nullable=True)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    # op.alter_column(u'users', 'password_hash',
    #            existing_type=sa.VARCHAR(length=128),
    #            nullable=False)
    # op.alter_column(u'users', 'email',
    #            existing_type=sa.VARCHAR(length=64),
    #            nullable=False)
    op.drop_table('tracking_items')
    op.drop_table('products')
    ### end Alembic commands ###
