"""empty message

Revision ID: 56da710fe1aa
Revises: 3e908863b911
Create Date: 2015-10-08 13:38:16.152000

"""

# revision identifiers, used by Alembic.
revision = '56da710fe1aa'
down_revision = '282e06799d08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_name', sa.String(length=20), nullable=False),
                    sa.Column('sn', sa.String(length=20), nullable=False),
                    sa.Column('power_input', sa.String(length=100)),
                    sa.Column('drive_gas', sa.String(length=100)),
                    sa.Column('acgo', sa.String(length=100)),
                    sa.Column('aux_o2', sa.String(length=100)),
                    sa.Column('aux_gas', sa.String(length=100)),
                    sa.Column('pipeline', sa.String(length=100)),
                    sa.Column('cylinder', sa.String(length=100)),
                    sa.Column('display_unit', sa.String(length=100)),
                    sa.Column('pmb', sa.String(length=100)),
                    sa.Column('acb', sa.String(length=100)),
                    sa.Column('fib', sa.String(length=100)),
                    sa.Column('sib', sa.String(length=100)),
                    sa.Column('vent_engine', sa.String(length=100)),
                    sa.Column('breathing_system', sa.String(length=100)),
                    sa.Column('agss', sa.String(length=100)),
                    sa.Column('ac_outlet', sa.String(length=100)),
                    sa.Column('transformer', sa.String(length=100)),
                    sa.Column('bag_arm', sa.String(length=100)),
                    sa.Column('sw', sa.String(length=100)),
                    sa.Column('others', sa.String(length=100)),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
                    sa.Column('last_updated_by', sa.Integer),
                    sa.PrimaryKeyConstraint('id')
                    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machines')
    ### end Alembic commands ###
